version: "3.9"

services:
  atlas-database:
    image: postgres:18-alpine
    container_name: atlas-container
    restart: unless-stopped
    environment:
      TZ: "UTC"
      PGTZ: "UTC"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      -  pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - atlas-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  atlas-network:
    driver: bridge

volumes:
  pgdata:
